//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdnHotelMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agencia
    {
        public Agencia()
        {
            this.Hospedagem = new HashSet<Hospedagem>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Hospedagem> Hospedagem { get; set; }
    }
}
